# NumPy

## Create a rank 1 array

In [24]:
import numpy as np
a = np.array([10,20,30, 40, 50])
print(type(a))

<class 'numpy.ndarray'>


In [10]:
print(a.shape)

(5,)


In [12]:
print(a[0], a[1], a[4])

10 20 50


In [13]:
a[0] = 15
print(a)

[15 20 30 40 50]


## Create a rank 2 array

In [20]:
b = np.array([[1, 3, 5], [2, 4, 6]])
print(b.shape)

(2, 3)


In [26]:
print(b[0, 0], b[0, 1], b[1, 1])

1 3 4


## Some numpy function

In [27]:
# Create an array of all zeros
a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [32]:
# Create an array of all ones
b = np.ones((2, 3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]


In [34]:
# create a constant array
c = np.full((2, 2), 5)
print(c)

[[5 5]
 [5 5]]


In [35]:
# create a 2x2 Identity matrix
d = np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


In [36]:
d2 = np.eye(3)
print(d2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [38]:
# create an array filled with random values
e = np.random.random((2,2))
print(e)

[[0.94548472 0.45184571]
 [0.3820447  0.67772403]]


In [39]:
e2 = np.random.random((2,3))
print(e2)

[[0.97239266 0.0044399  0.62875813]
 [0.34156109 0.56974609 0.66218622]]


# Array Indexing
## Slicing

In [41]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
a = np. array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [42]:
# Use slicing to pull out the subarray consisting of the first 2 rows and columns 1 and 2; b is the following array of shape (2, 2):
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


In [52]:
# A slice of an array is a view into the same data, so modifying it will  modify the original array
print(a[0, 1])

2


In [53]:
print(a[0, 1])
b[0, 0] = 20
print(a[0, 1])

2
20


## Integer Array Indexing

In [59]:
import numpy as np
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [63]:
# Example of integer array indexing
# The new array will have shape(3, )
print(a[[0, 1, 2], [0, 1, 0]])

[1 4 5]


In [61]:
# Which is equivalent to this one
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 5]


In [64]:
# We can also write in this way [Plain old indexing]
print(np.array([a[0][0], a[1][1], a[2][0]]))

[1 4 5]


In [ ]:
#  Create sequence of array using 'arange' function
sequence = np.arange(4)
print(sequence)

## Indexing in other way

In [66]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## Array Indexing using Boolean expression

In [68]:
a = np.array([[1, 2], [3, 4], [5, 6]])

bool_idx = (a > 2)
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [69]:
print(a[bool_idx])

[3 4 5 6]


In [70]:

print(a[a > 2])

[3 4 5 6]


## Datatypes

In [72]:
import numpy as np

x = np.array([1, 2])
print(x.dtype)

int64


In [74]:
x = np.array([1.0, 2.0])
print(x.dtype)

float64


In [79]:
x = np.array([1, 2], dtype=np.float64)
print(x.dtype)

float64


## Array Math

In [81]:
import numpy as np

x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)

# Element wise sum; both produce this array
print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [83]:
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [84]:
# Element wise subtraction
print(x -y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [85]:
# Element wise multiplication
print(x*y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [86]:
# Element wise division
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [88]:
# Element wise Square root
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


## Matrix Operations
### Dot Product of vectors

## Dot product of Matrices/ Multiplication of Matrices

In [89]:
import numpy as np

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

In [91]:
# Inner product of vectors
print(v.dot(w))

print(np.dot(v, w))

219
219


In [92]:
# Matrix/vector product:
print(x.dot(v))
print(np.dot(x, v))

[29 67]
[29 67]


In [95]:
# print(np.cross(v,w))


-2


In [96]:
# Matrix / matrix product; both produce the rank 2 array
print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


## Sum of all elements or column wise sum

In [98]:
import numpy as np

x = np.array([[1, 2], [3, 4]])

# Compute sum of all elements
print(np.sum(x))

10


In [99]:
# Compute sum of each column
print(np.sum(x, axis=0))


[4 6]


In [100]:
# Compute sum of each row
print(np.sum(x, axis=1))

[3 7]


## Broadcasting

In [101]:
import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])

# We will now add the vector 'v' to each row of the matrix 'x'
# Storing the result in the matrix 'y'

# Create an empty matrix with the same shape as 'x'
y = np.empty_like(x)

In [102]:
# Add the vector 'v' to each row of the matrix 'x' with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

In [103]:
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [104]:
# Stacking 4 copies of 'v' on top of each other [4 -> 4 rows, 1 -> 1 rows]
vv = np.tile(v, (4, 1))

print(vv)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [105]:
# Adding elementwise
y = x + vv
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [106]:
# Broadcasting in Numpy

import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])

In [110]:
y = x + v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


## Application of Broadcasting

In [111]:
import numpy as np

v = np.array([1, 2, 3])
w = np. array([4, 5])

print(v)
print(w)

[1 2 3]
[4 5]


In [112]:
print(v.reshape(3, 1) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [113]:
# Add a vector to each row of a matrix
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x + v)

[[2 4 6]
 [5 7 9]]


In [114]:

z = x.T + w

print(z)

[[ 5  9]
 [ 6 10]
 [ 7 11]]


In [115]:
print(z.T)

[[ 5  6  7]
 [ 9 10 11]]
